### ISSUE TITLE
Latex / markdown and python issue. 

### ISSUE THREAD

**Issue by vsedov** [mireq/luasnip-snippets#1]
Nice plugin although some refining is required. 
![image](https://github.com/mireq/luasnip-snippets/assets/28804392/5563ceb3-37de-4894-b492-afe828407e22)

for latex files and for python 

![image](https://github.com/mireq/luasnip-snippets/assets/28804392/e3187f9d-acde-4464-ab47-9788566df1c3)

Markdown also has a similar issue 

![image](https://github.com/mireq/luasnip-snippets/assets/28804392/d7252906-8dc6-4d72-82e0-66586d8dc6d2)

**Comment by mireq** [comment]
@vsedov i have posted some fixes, try it now

**Comment by vsedov** [comment]
Works so far, il reopen it, based on further usage, thanks for your work .
