### ISSUE TITLE
Broken Go snippets

### ISSUE THREAD

**Issue by mawkler** [mireq/luasnip-snippets#7]
Hi! Thanks for making this plugin!

I'm having issues with some Go snippets. In particular the `func` and `if`.

**`func`:**

```go
func name(params)typetype {

}
```

Note that `type` appears twice, but only the second one is an insert node. The first `type` changes to whatever I insert into the second one.

**`if`:**

```go
if conditioncondition{

}
```

Similarly to `func`, `if` also has the `condition` repeated. The first `condition` is an insert node, and the second `condition` changes to whatever I insert into the first one.

**Comment by mawkler** [comment]
Also, the `meth` Go snippet doesn't even expand for some reason

**Comment by mireq** [comment]
@mawkler please test it with minimal configuration (or with cmp) from this sample directory - [sample_configs](https://github.com/mireq/luasnip-snippets/tree/main/sample_configs)

If it works, then problem is somewhere in configuration, maybe some conflict with other plugin. Try to make minimal config to reproduce that bug.

**Comment by mawkler** [comment]
@mireq I get the exact same behaviour when using your minimal config [`cmp_lazy.lua`](https://github.com/mireq/luasnip-snippets/blob/main/sample_configs/cmp_lazy.lua)

**Comment by mireq** [comment]
@mawkler if you can try it on empty user profile without `~/.config/nvim` directory and `~/.local/share/nvim`. If problem persists, please check nvim and nvim python bridge version. I will try to reproduce bug with same version.

**Comment by mawkler** [comment]
@mireq 

> try it on empty user profile

Could you please elaborate on what you mean by this? I ran `nvim -u path/to/your/config`, is there anything else that I need to do?

**Comment by mireq** [comment]
@mawkler sorry for dealy, i have forgotten ths comment, too much work.

So `nvim -u path/to/your/config` should start nvim with custom config path instad of `.config/nvim/init.lua`.

**Comment by mawkler** [comment]
No worries!

> `nvim -u path/to/your/config`

That's what I did when I was trying both your minimal configs [`cmp_lazy.lua`](https://github.com/mireq/luasnip-snippets/blob/main/sample_configs/cmp_lazy.lua) and [`minimal_lazy.lua`](https://github.com/mireq/luasnip-snippets/blob/main/sample_configs/minimal_lazy.lua), and I got the same bug 🙂

**Comment by mireq** [comment]
@mawkler try check nvim version (nvim -v). Try checkhealth. Check python version.

**Comment by mawkler** [comment]
@mireq Good call! `:checkhealth luasnip` gave me the following warning:

```
- WARNING             For Variable/Placeholder-transformations, luasnip requires
              the jsregexp library. See `:help |luasnip-lsp-snippets-transformations`| for advice
```

Adding `run = 'make install_jsregexp'` to my LuaSnip lazy.nvim config solves it. I noticed now that your example configs also included that line, but my guess is that `run` doesn't run if you already have the plugin installed (which I did).

Anyway, thanks for the help!
